name: shimmer_x
description: A customizable shimmer loading effect for Flutter.
version: 1.0.10
homepage: https://github.com/mriyas/shimmer_x
repository: https://github.com/mriyas/shimmer_x
issue_tracker: https://github.com/mriyas/shimmer_x/issues
publish_to: https://pub.dev

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
