name: shimmer_x
description: A customizable shimmer loading effect for Flutter.
version: 1.0.10
homepage: https://github.com/mriyas/shimmer_x
repository: https://github.com/mriyas/shimmer_x
issue_tracker: https://github.com/mriyas/shimmer_x/issues
documentation: https://github.com/mriyas/shimmer_x#readme

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

# Recommended for pub.dev discoverability
topics:
  - shimmer
  - loading
  - placeholder
  - animation
  - flutter